### PR TITLE
remove post cloner

### PR DESCRIPTION
**Pull request by jazzsequence**
This updates the composer installer overrides to remove Post Cloner in preparation of replacing with Yoast Duplicate Post.
We don't need to add Yoast Duplicate Post to replace here because manually overriding in the override installer class is no longer required.

### CODE REVIEW

**Comment by roborourke** [comment]
We don't need these updates any more but makes sense to remove the post cloner item in case it falls back to this list. We should modify the docs around adding dependencies.

**Comment by jazzsequence** [comment]
We don't need to update core for the install path for dependencies anymore?

**Comment by roborourke** [comment]
Yeah that’s what Ryan spent ages sorting back for v6 so we didn’t have this to do this anymore :) Use the `install-overrides` property in the module’s composer file

**Comment by jazzsequence** [comment]
🤯

**Comment by jazzsequence** [comment]
That just made this PR a whole lot simpler 🙄

**Comment by jazzsequence** [comment]
Marking this ready for review now since it's a single line that's not really necessary anymore anyway and doesn't impact anything else.

**Review by roborourke — APPROVED** [review]

**Pull request merged**
